# Generated by Django 6.0.4 on 2026-04-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('published', 'Публічна публікація')], default='draft', max_length=10),
        ),
    ]
